name: URL Shortener CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


concurrency:
  group: url-shortener-pipeline
  cancel-in-progress: true


env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: url-shortener
  HELM_VALUES: helm/url-shortener/values.yaml


jobs:


  test:

    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Tests
      run: |
        pytest -v


    - name: Coverage
      run: |
        pytest --cov=. --cov-report=term-missing



  build:


    needs: test

    runs-on: self-hosted


    steps:


    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region: ${{ env.AWS_REGION }}



    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2



    - name: Build Docker Image

      run: |

        docker build \
        -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .



    - name: Trivy Security Scan

      uses: aquasecurity/trivy-action@0.35.0

      with:

        image-ref: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

        severity: HIGH,CRITICAL

        exit-code: 0



    - name: Push Image To ECR

      run: |


        docker push \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}




  update-manifest:


    needs: build

    runs-on: self-hosted


    steps:


    - name: Checkout Code

      uses: actions/checkout@v4



    - name: Update Helm Image Tag

      run: |


        sed -i \
        "s/tag:.*/tag: \"${{ github.sha }}\"/" \
        ${{ env.HELM_VALUES }}



    - name: Commit Helm Change


      run: |


        git config --global user.name "github-actions"

        git config --global user.email "github-actions@github.com"


        git add .

        git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes"

        git push
